config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create]
  resources :subs, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :moderator,
    class_name: 'User',
    primary_key: :id,
    foreign_key: :user_id
  )

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :password_digest, presence: true
  validates :name, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  after_initialize :ensure_session_token
  attr_reader :password

  has_many(
    :subs,
    class_name: 'Sub',
    primary_key: :id,
    foreign_key: :user_id
  )

  def password=(pword)
    self.password_digest = BCrypt::Password.create(pword)
  end

  def is_password?(pword)
    BCrypt::Password.new(password_digest).is_password?(pword)
  end

  def self.find_by_credentials(name, pword)
    user = User.find_by(name: name)
    return user if user && user.is_password?(pword)
    nil
  end

  def reset_session_token!
    self.session_token = generate_unique_token
    self.save!
  end

  def ensure_session_token
    self.session_token ||= generate_unique_token
  end

  private


  def generate_unique_token
    new_token = SecureRandom.base64
    while User.exists?(session_token: new_token)
      new_token = SecureRandom.base64
    end
    new_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?

  def login_user!
    if @user
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      redirect_to subs_url
    else
      flash[:errors] = "Invalid username or password"
      redirect_to new_session_url
    end
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  private

  def user_params
    params.require(:user).permit :name, :password
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:name], user_params[:password])
    login_user!
  end

  def destroy
    logout_user!
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    render :index
  end

  def new
    if logged_in?
      @sub = Sub.new
      render :new
    else
      escape
    end
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = ["Not a valid subrequest."]
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit :title, :description, :user_id
  end

  def escape
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid user input"]
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
      <input
        type="hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}"
        >
    HTML
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<% if logged_in?%>
  <%= "Welcome to Breddit, #{current_user.name}" %>
<form action="<%= session_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Log Out">
</form>

<% else %>
<form action="<%= new_session_url %>" method="get">
  <%= auth_token %>
  <input type="submit" value="Log In">
</form>

<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

app/views/subs/_form.html.erb
<% method = @sub.persisted? ? :edit : :post %>
<% action = @sub.persisted? ? "edit_sub_url(@sub)" : "sub_url(@sub)"  %>

<form action= "<%= "#{action}" %>" method="<%= method %>">
  <%= auth_token %>
  <label for="sub_title">Subbreddit Title: </label>
    <input
      type="text"
      name="sub[title]"
      value=""
      id="sub_title">
      <br>
      <br>
  <label for="description">Description: </label>
      <br>
    <textarea
      name="sub[description]"
      rows="8"
      cols="37"
      id="description"><%= @sub.description %></textarea>
      <br>
      <br>
    <input
      type="hidden"
      name="sub[user_id]"
      value="<%= current_user.id %>">

<button type="submit" name="submit">Bake this Subbreddit</button>
</form>

app/views/subs/index.html.erb
<h3>Every Kind of Subbreddit You Could Ever Eat a Loaf Off of</h3>
<ul>

<% Sub.all.each do |loaf| %>
  <li>
  <%= link_to loaf.title, sub_url(loaf.id) %>
  </li>
<% end %>

</ul>

<%= link_to "Bake a new Subbreddit", new_sub_url %>

app/views/subs/new.html.erb
<h2>Create a new Subbreddit</h2>
<%= render "shared/errors" %>
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p>
  <%= @sub.description %>
</p>
<br>
______________________________
<br>
<%= "Moderator: #{User.find(@sub.moderator).name}" %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<form action= "<%= users_url(@user) %>" method="post">
  <%= auth_token %>
  <label for="user_name">Username: </label>
    <input
      type="text"
      name="user[name]"
      value=""
      id="user_name">
      <br>
      <br>
  <label for="password">Password: </label>
    <input type="password"
      name="user[password]"
      value=""
      id="password">
      <br>
      <br>

<button type="submit" name="submit">Commence Bread Enthusiast Status</button>
</form>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>